# This is a config for E2B sandbox template.
# You can use template ID (z4y0oy23me4f4gdfnnyx) or template name (vicod-nextjs-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vicod-nextjs-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("vicod-nextjs-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vicod-nextjs-test')

team_id = "6f7e9854-c3fa-4eb2-ab0b-0781f0aac873"
start_cmd = "/home/user/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vicod-nextjs-test"
template_id = "z4y0oy23me4f4gdfnnyx"
